Documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'
  - any-glob-to-any-file: 'docs/**'

# Add 'feature' label to any PR where the head branch name starts with `feature` or has a `feature` section in the name
feature:
 - head-branch: ['^feature', 'feature']

# Add 'bug' label to any PR where the head branch name starts with `bug` or has a `bug` section in the name
bug:
 - head-branch: ['^bug', 'bug']
